# Site settings
author: Aaron Harvey
title: Flatiron - Or How I stopped coasting and took control of my career
header-img: img/home-bg.png
email: harvey.aaronj@gmail.com
copyright_name: Aaron Harvey
description: > # this means to ignore newlines until "baseurl:"
  My journey into Coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AaronJHarvey

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
